### ISSUE TITLE
喝茶

### ISSUE THREAD

**Issue by ty201115** [MAWHA/MWA#2]
有做品茗功能的计划吗，实在不想去猜器者的想法了

**Comment by zhouxinghua001** [comment]
> 有做品茗功能的计划吗，实在不想去猜器者的想法了

品茗的前两个选最后一个，只需要每个器者记一个就行

**Comment by Despair21** [comment]
其实也不用去猜，可以去bilibili的wiki上去看

**Comment by WeiYuFei0217** [comment]
> > 有做品茗功能的计划吗，实在不想去猜器者的想法了
> 
> 品茗的前两个选最后一个，只需要每个器者记一个就行

确实，能不能先最后两个随便选？也不太影响好感度

**Comment by ty201115** [comment]
> > > 有做品茗功能的计划吗，实在不想去猜器者的想法了
> > 
> > 
> > 品茗的前两个选最后一个，只需要每个器者记一个就行
> 
> 确实，能不能先最后两个随便选？也不太影响好感度

我倒是不急，主要是其它玩法我自己可以打，品茗这种无聊又硬控我的就想偷懒

**Comment by zhouxinghua001** [comment]
> > > > 有做品茗功能的计划吗，实在不想去猜器者的想法了
> > > 
> > > 
> > > 品茗的前两个选最后一个，只需要每个器者记一个就行
> > 
> > 
> > 确实，能不能先最后两个随便选？也不太影响好感度
> 
> 我倒是不急，主要是其它玩法我自己可以打，品茗这种无聊又硬控我的就想偷懒

奖励一般，还逼你看动画···

**Comment by mmwuyou** [comment]
喜报~喝茶能用版本已经写好了，很快就可以发版了（1.3.6）
