### ISSUE TITLE
派遣公司有bug

### ISSUE THREAD

**Issue by longshensanjie** [MAWHA/MWA#4]
派遣公司选择金色石墨条，运行到选择石墨条界面之后会卡住，之后的功能也会都卡在这里
[maa.log](https://github.com/user-attachments/files/16347342/maa.log)

**Comment by mmwuyou** [comment]
> 派遣公司选择金色石墨条，运行到选择石墨条界面之后会卡住，之后的功能也会都卡在这里 [maa.log](https://github.com/user-attachments/files/16347342/maa.log)

https://github.com/MAWHA/MWA/actions/runs/10061034260

链接进去往下拉，下载替换看看

**Comment by longshensanjie** [comment]
@mmwuyou ok，新版本可用，没问题，感谢辛苦付出，另外使用下来提几点建议
1. 易物所随机易市会自动购买完全没打折的商品，用户能否自己设置（比如绿材料多少折扣以下才会购买，其他品质材料类似）
2. 派遣公司会自动领取存的体力，这里能否自己设置是否需要领取
3. 博物致学功能使用必须提前设置战斗自动，能否在博物致学功能之中自动识别设置战斗自动，这样更方便使用

**Comment by mmwuyou** [comment]
> @mmwuyou ok，新版本可用，没问题，感谢辛苦付出，另外使用下来提几点建议
> 
> 1. 易物所随机易市会自动购买完全没打折的商品，用户能否自己设置（比如绿材料多少折扣以下才会购买，其他品质材料类似）
> 2. 派遣公司会自动领取存的体力，这里能否自己设置是否需要领取
> 3. 博物致学功能使用必须提前设置战斗自动，能否在博物致学功能之中自动识别设置战斗自动，这样更方便使用

ok，下次发版带上这个修复，回复第一点，因为当时只想着能够任意买一个东西完成任务就行，其次基于picli的限制，后面会尽可能的改进。第二点，当时想着每一次挂上去都会清体力这样子，所以没有独立出来，直接默认领取就完事了，后续也可以独立。第三点，你说的这个并不是没有考虑到，而是跟任务"喝水"一样，因此直接给去掉了，后续想到解决办法会加进去的

**Comment by longshensanjie** [comment]
@mmwuyou ok
