### ISSUE TITLE
[bug] 演训  冬谷五速刷卡死在演训界面

### ISSUE THREAD

**Issue by longshensanjie** [MAWHA/MWA#7]
演训冬谷五速刷卡死在演训界面，配置参数如下截图，附带log，经测试其他速刷也存在同样问题

![屏幕截图 2024-08-01 155739](https://github.com/user-attachments/assets/8f843c4b-fe86-4bbc-b865-86477788e7e6)
[maa.log](https://github.com/user-attachments/files/16452117/maa.log)

**Comment by mmwuyou** [comment]
https://github.com/MAWHA/MWA/actions/runs/10221446830
往下拉到底，下载后替换试试看，有问题再回来说并带上log，没问题也说一下，下次发版带上

**Comment by longshensanjie** [comment]
@mmwuyou ok，记住了，替换后没问题
