### ISSUE TITLE
mwa运行任务无反应

### ISSUE THREAD

**Issue by xiaovoaix** [MAWHA/MWA#8]
![image](https://github.com/user-attachments/assets/886901b4-4506-499d-bccf-e14146991ad6)
![image](https://github.com/user-attachments/assets/5c51b189-0b7e-4e87-b657-d524228eb8ca)
模拟器停在此画面无反应
其他任务也是这样（启动应用倒是能实现，但是公告关不上）
[maa.log](https://github.com/user-attachments/files/16455626/maa.log)

mwa版本v1.3.3
mumu版本v4.0.0(3179)

试了试maa debugger，可以正常使用
![image](https://github.com/user-attachments/assets/dd78b673-e3d4-479a-bf70-7690e9bad64a)

**Comment by mmwuyou** [comment]
debugger能正常的话，picli的时候抽风？看看log先

**Comment by mmwuyou** [comment]
有其他任务的log也给一下

**Comment by mmwuyou** [comment]
模拟器分辨率在1280*720或720*1280及其以上不

**Comment by xiaovoaix** [comment]
> 模拟器分辨率在1280_720或720_1280及其以上不

![image](https://github.com/user-attachments/assets/0b8ffb9a-37cb-4f91-b4ae-75e31d1652b9)

**Comment by xiaovoaix** [comment]
> 有其他任务的log也给一下

![image](https://github.com/user-attachments/assets/b10a6f55-1dc4-4d5e-b709-e4b7bb9aa873)

[maa.log](https://github.com/user-attachments/files/16476922/maa.log)

**Comment by mmwuyou** [comment]
![QQ图片20240803121824](https://github.com/user-attachments/assets/3ea019bd-ff66-4105-bb68-841ac39106e2)
你这怎么看起来像在桌面

**Comment by xiaovoaix** [comment]
> ![QQ图片20240803121824](https://private-user-images.githubusercontent.com/142766247/354791602-3ea019bd-ff66-4105-bb68-841ac39106e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTkxNDUsIm5iZiI6MTcyMjY1ODg0NSwicGF0aCI6Ii8xNDI3NjYyNDcvMzU0NzkxNjAyLTNlYTAxOWJkLWZmNjYtNDEwNS1iYjY4LTg0MWFjMzkxMDZlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwM1QwNDIwNDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmNiMDQzOWE5NTc2ZjljYzg4MTIyNmEyYTA1YzQ4NTVlOWEzOWY5ODNhNGQwODhkZWE4NzYyMjUxMjgwZjQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iIdLv5xEWtmX3Y2L8-tQt6Wz6BnMte7SgTY3mfxzcKA) 你这怎么看起来像在桌面

我不道啊，模拟器确实已经打开游戏了;(

**Comment by xiaovoaix** [comment]
@mmwuyou 知道了，是mumu的多标签模式的问题
![image](https://github.com/user-attachments/assets/78ccab05-4bce-4541-a49a-ea829f4c1184)
应该picli读的是Main窗口，所以才有问题

**Comment by mmwuyou** [comment]
![image](https://github.com/user-attachments/assets/daffd17e-3ab8-45bf-8df2-41edb0190659)
这个开了的话，也关了它

**Comment by xiaovoaix** [comment]
已经一起关了，所以为什么debugger没问题呢（）

**Comment by mmwuyou** [comment]
> 知道了，是mumu的多标签模式的问题 ![图像](https://private-user-images.githubusercontent.com/58628662/354791840-78ccab05-4bce-4541-a49a-ea829f4c1184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTk1NTYsIm5iZiI6MTcyMjY1OTI1NiwicGF0aCI6Ii81ODYyODY2Mi8zNTQ3OTE4NDAtNzhjY2FiMDUtNGJjZS00NTQxLWE0OWEtZWE4MjlmNGMxMTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA0MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMjg3NmU2MmUzOThlYzJmZTM1YTMxZGY4YjM4MjZkYzE3MjY3YzM3NmQwNTMwMTMxMzNiYjcyNDhhZmQ3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uYd3SDmUEJb4hMyr0f1qdEYy56R-GvQrWi0wAambobI) 应该picli读的是Main窗口，所以才有问题 应该算bug吧（）

跟这个没关系吧，我一直都开着，也没你这问题

**Comment by mmwuyou** [comment]
> 已经一起关了，所以为什么debugger没问题呢（）

都关了，跑过没

**Comment by xiaovoaix** [comment]
> > 已经一起关了，所以为什么debugger没问题呢（）
> 
> 都关了，跑过没

试过了，可以正常运行

**Comment by xiaovoaix** [comment]
> > 知道了，是mumu的多标签模式的问题 ![图像](https://private-user-images.githubusercontent.com/58628662/354791840-78ccab05-4bce-4541-a49a-ea829f4c1184.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NTk1NTYsIm5iZiI6MTcyMjY1OTI1NiwicGF0aCI6Ii81ODYyODY2Mi8zNTQ3OTE4NDAtNzhjY2FiMDUtNGJjZS00NTQxLWE0OWEtZWE4MjlmNGMxMTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA0MjczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmMjg3NmU2MmUzOThlYzJmZTM1YTMxZGY4YjM4MjZkYzE3MjY3YzM3NmQwNTMwMTMxMzNiYjcyNDhhZmQ3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uYd3SDmUEJb4hMyr0f1qdEYy56R-GvQrWi0wAambobI) 应该picli读的是Main窗口，所以才有问题 应该算bug吧（）
> 
> 跟这个没关系吧，我一直都开着，也没你这问题

那应该就是那个后台保活的问题（）
